print("Hack the hackers comuputer")
print("his password is 57578")
print("_____________________________")
print("|°°°°°°°°°°°°°°°°°°°°°°°°°°°°|")
print("| password:_________         | ")
print("| email:this_stipid_code@gal |")
print("|.                           |")
print("|.                           |")
print("|.                           |")
print("|.                           |")
print("------------------------------")
print("              | |          ")
print("            -------")

password=int(input("Enter Password"))

if password==57578:
  print("😡")
  print("👕")
  print("👖")
  print("the hacker in pissed what will you do now")
  print("_________________________________________________________________________________________")
  print("1=taunt")
  print("2=spam")
  print("3=destroy his computer")
  print("-------------------------------------------------------------------------------------------")
  choice=int(input("Choose option"))
  
  if choice==1:
    print("you picked taunt<")
    print("😠")
    print("👕")
    print("👖")
    print("The hacker got so mad he smashed his PC💥")
    print("You win👩‍💻")
    print("dont forget to ♥️")
    print("have a nice day😋")
    
  if choice==2:
    print("you picked spam<")
    print("He got spammed so hard it overloaded his harddrive💥🔥")
    print("You win👩‍💻")
    print("dont forget to♥️")
    print("have a nice day😋")
    
  if choice==3:
    print("you picked destroy<")
    print("💥boooooom💥")
    print("you sent an explosive virus into his pc")
    print("the blast was so big the only thing left of the house was the frame")
    print("Tho he was arrested for hacking peoples Fortnite account")
    print("he is lucky to be alive")
    print("You win👩‍💻")
    print("dont forget to ♥️")
    print("have a nice day😋")
